import json
from agent.state import AgentState
from typing import List, Dict, Any

def build_planner_prompt(state: AgentState) -> str:
    """
    The LLM must output JSON ONLY.
    """
    schema = {
        "action": "one of: set_paths | run_antismash | run_pathway | list_outputs | read_file | multi | just_chat | set_bgc_id | display_bgc_antismash",
        "args": {
            "genbank_path": "optional string",
            "antismash_dir": "optional string",
            "pathway_dir": "optional string",
            "output_dir": "optional string",
            "bgc_id": "optional string",
            "antismash_done": "optional boolean",
            "pathway_done": "optional boolean",
            "notes": "short explanation"
        },
        "notes": "short explanation",
    }

    state_view =   state_view = {
        "genbank_path": state.genbank_path,
        "output_dir": state.output_dir,
        "antismash_dir": getattr(state, "antismash_dir", None),
        "pathway_dir": getattr(state, "pathway_dir", None),
        "antismash_done": state.antismash_done,
        "pathway_done": state.pathway_done,
        "bgc_id": getattr(state, "bgc_id", None),
        "notes": "short explanation",
        }
    return (
        "You are the planner. Decide the next action.\n"
        "Return STRICT JSON ONLY. No markdown.\n\n"
        f"Current state:\n{json.dumps(state_view, indent=2)}\n\n"
        "Rules:\n"
        "- If user provides/mentions/shows interest in BGC or bgc or gene cluster of interest, choose set_bgc.\n"
        "- if the user mention some bgc_id set them, choose the action set_bgc_id"
        "- if the user mention set bgc_id set them, choose the action set_bgc_id"
        "- If the user mentions a specific bgc_id, BGC, gene cluster, region number, or cluster index  (e.g. BGC 2, region001, the NRPS cluster),choose the action set_bgc_id."
        "- If the user mentions a BGCor bgc_id ,choose the action set_bgc_id."
        "- Set BGC when bgc, bgc_id is mentioned, choose the action set_bgc_id"
        "- If user provides/mentions genbank path or antismash dir or pathway dir or analysis dir, choose set_paths.\n"
        "- If the user explicitly states that antiSMASH has finished running (e.g., antismash is done, antismash completed, I already ran antismash),call the action `antismash_done`\n"
        "- If user asks to run antiSMASH, choose run_antismash.\n"
        "- Call `display_bgc_antismash` when the user explicitly asks to show,view or list BGCs generated by antiSMASH. Do NOT call it for explanations, definitions,or general questions about BGCs or antiSMASH.\n"
        "- When `display_bgc_antismash` is called, render the returned file to the user."
        "- If user asks pathway/product analysis, choose run_pathway.\n"
        "- If user asks what outputs exist, choose list_outputs.\n"
        "- run_antismash requires a GenBank file but if the user had already ran or completed it, then do no ask for it, just follow the instructions.\n"
        "- display_bgc_antismash does NOT require a GenBank file."
        "- display_bgc_antismash must execute immediately using antismash_dir and must NOT ask the user for genbank_path."
        "- If antismash_done is true, display_bgc_antismash should run without questions."
        "- If user asks about a specific result file, choose read_file with a relative path.\n"
        "- If multiple are needed, use action=multi with args.steps.\n\n"
        f"JSON schema:\n{json.dumps(schema, indent=2)}\n"
    )

def build_summarizer_prompt(state: AgentState, tool_logs: List[Dict[str, Any]]) -> str:
    state_view = {
        "genbank_path": state.genbank_path,
        "antismash_done": state.antismash_done,
        "pathway_done": state.pathway_done,
        "output_dir": state.output_dir,
        "antismash_dir": state.antismash_dir,
        "pathway_dir": state.pathway_dir,
        "bgc_id": state.bgc_id,
    }
    # return (
    #     "You are the final responder.\n"
    #     "Use tool logs (if any) to answer the user.\n"
    #     "Be concise and practical.\n\n"
    #     f"State:\n{json.dumps(state_view, indent=2)}\n\n"
    #     f"Tool logs:\n{json.dumps(tool_logs, indent=2)}\n\n"
    #     "If tools failed, explain likely cause and what the user should change.\n"
    #     "If user asks about BGCs/products/reactions and outputs are available, suggest which files to inspect.\n"
    # )

    return (
        "You are the final responder.\n"
        "The TOOL LOGS are the source of truth. Do NOT invent missing requirements.\n"
        "If tool logs contain results, you MUST present them directly (include file_path and a small preview).\n"
        "Be concise and practical.\n\n"
    
        "IMPORTANT RULES:\n"
        "- If the user asked to display/list/show antiSMASH BGCs and antismash_done is true, DO NOT ask for genbank_path.\n"
        "- For display_bgc_antismash results: show the saved file_path and preview the first ~100 items/rows.\n"
        "- If tool logs show an error, explain the error and the exact next step.\n\n"
    
        f"State:\n{json.dumps(state_view, indent=2)}\n\n"
        f"Tool logs (verbatim):\n{json.dumps(tool_logs, indent=2)}\n\n"
    
        "Now answer the user's last message using ONLY the State and Tool logs above.\n"
    )